name: integration-test-cli

# Trigger this workflow manually from the GitHub Actions tab
on:
  workflow_dispatch:

jobs:
  cli-integration-test:
    strategy:
      matrix:
        runner: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: restore pip cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('.github/ci-requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ matrix.python-version }}-
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # without cache: 'pip' here since we're using the cache action
      - name: Build wheel
        run: |
          python -m pip install -U pip
          python -m pip install -r .github/ci-requirements.txt
          python -m build -x -n --wheel
      - name: Install wheel
        run: python -m pip install dist/*.whl
      - name: Download test data
        run: wget https://storage.googleapis.com/varona-bucket/small.vcf
      - name: Run Varona CLI
        run: varona small.vcf small.csv
