name: codecov

on:
  push:
    branches:
      - "main"
    paths:
      - "src/**/*.py"
      - "setup.py"
      - "setup.cfg"
      - "pyproject.toml"
      - ".github/ci-requirements.txt"
      - ".github/workflows/codecov.yml"
      - ".github/workflows/unittest.yml"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: restore pip cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip-Linux-3.11-${{ hashFiles('.github/ci-requirements.txt') }}
          restore-keys: |
            pip-Linux-3.11-
      - name: set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: run tests and collect coverage
        run: |
          python -m pip install -U pip
          python -m pip install -r .github/ci-requirements.txt
          python -m unittest discover -s src -p "*_test.py"
          coverage run -m unittest discover -s src -p "*_test.py"
          coverage xml
      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
