name: pypi-deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: restore pip cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip-Linux-3.11-${{ hashFiles('.github/ci-requirements.txt') }}
          restore-keys: |
            pip-Linux-3.11-
      - name: set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - id: "auth"
        name: "Authenticate with Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS_JSON }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
      - name: build and upload to GCP artfiacts registry
        run: |
          python -m pip install -U pip
          python -m pip install -r .github/ci-requirements.txt
          python -m build
          twine upload --non-interactive --skip-existing --repository-url https://us-central1-python.pkg.dev/fiery-bit-428319-p1/pohlio-pypi/ dist/*
