name: Python Test

on:
  push:
  pull_request:
    paths:
      - "src/**/*.py"
      - "setup.py"
      - "setup.cfg"
      - "pyproject.toml"

jobs:
  build:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: restore pip cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('.github/ci-requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ matrix.python-version }}-
      - name: Run tests
        run: |
          python${{ matrix.python-version }} -m pip install -U pip
          python${{ matrix.python-version }} -m pip install -r .github/ci-requirements.txt
          python${{ matrix.python-version }} -m unittest discover -s src -p "*_test.py"
